//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class tblUserLogin
    { 
        [Key]
        public int Login_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Email { get; set; }
        public string Pwd { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
